name: docs

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'docs'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            package:
              - 'packages/docs/**'

      - name: Setup pages
        if: steps.changes.outputs.package == 'true'
        uses: actions/configure-pages@v2

      - name: Install dependencies
        if: steps.changes.outputs.package == 'true'
        run: yarn install --immutable

      - name: Build
        if: steps.changes.outputs.package == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn workspace @navigare/docs run build

      - name: Upload artifacts
        if: steps.changes.outputs.package == 'true'
        uses: actions/upload-pages-artifact@v1
        with:
          path: packages/docs/src/.vitepress/dist/

      - name: Deploy to GitHub Pages
        if: steps.changes.outputs.package == 'true'
        id: deployment
        uses: actions/deploy-pages@v1
