name: release

on:
  push:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn workspace @navigare/docs build

      - name: Release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: publish documentation'
          file_pattern: 'packages/docs'
