name: publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package
        required: true
        default: '@navigare/core'
        type: choice
        options:
          - '@navigare/core'
          - '@navigare/laravel'
          - '@navigare/ssr'
          - '@navigare/vite'
          - '@navigare/vue3'
#  push:
#    branches:
#      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn workspace ${{ inputs.package }} npm publish --access public
