name: release

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - '@navigare/core'
          - '@navigare/ssr'
          - '@navigare/vite'
          - '@navigare/vue3'
          - '@navigare/laravel'
      fail-fast: false
      max-parallel: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DEBUG: 'semantic-release:*'
        run: yarn workspace ${{ matrix.package }} run release
