name: release

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - laravel
          - core
          - ssr
          - vite
          - vue3
      fail-fast: false
      max-parallel: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Get changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            package:
              - 'packages/${{ matrix.package }}/**'

      - name: Install dependencies
        if: steps.changes.outputs.package == 'true'
        run: yarn install --immutable

      - name: Release
        if: steps.changes.outputs.package == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DEBUG: 'semantic-release:*'
        run: yarn workspace @navigare/${{ matrix.package }} run release
